workflows:
  cordova-android:
    name: Cordova Android Workflow by hci bundel
    environment:
      node: latest
    scripts:
      - name: Install Dependencies
        script: |
          echo "stepmen: Install Dependencies"
          echo "install npm required"
          npm install
          npm ci
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 11.0.20-amzn
          sdk install gradle 7.1.1
          echo "stepmen: Install Dependencies completed."

      - name: Add Android Platform
        script: |
          echo "stepmen: Add Android Platform"
          cordova platform add android
          echo "stepmen: Add Android Platform completed."

      - name: Build Bundle
        script: |
          echo "stepmen: Build Bundle"
          echo "create keystore"
          keytool -genkeypair -v -keystore wolf.keystore -storepass @loopback211 -keyalg RSA -keysize 2048 -validity 10000 -alias lgarin211 -storetype PKCS12 -dname "CN=agus, OU=tinus, O=tobing, L=id, ST=id, C=id"
          echo "build bundle"
          cordova build android --release -- --keystore=./wolf.keystore --storePassword=@loopback211 --alias=lgarin211 --password=@loopback211 --packageType=bundle
          echo "stepmen: Build Bundle completed."

      - name: Compress
        script: |
          echo "stepmen: Compress"
          echo "Compresing..."
          mkdir uploadfile
          cp -r platforms uploadfile
          cp -r wolf.keystore uploadfile
          zip ready.zip uploadfile
          echo "stepmen: Compress completed."

      - name: Upload APK
        script: |
          echo "stepmen: Upload APK"
          echo "Deploying app to Codemagic..."
          curl -v -X POST \
            -F "file=@ready.zip" \
            -H "x-auth-token: $CM_API_TOKEN" \
            -H "content-type: multipart/form-data" \
            https://api.codemagic.io/artifacts/upload
          echo "stepmen: Upload APK completed."
artifacts:
  - /file=/Users/builder/clone/ready.zip
publishing:
  email:
    recipients:
      - lagustinus211@gmail.com
