workflows:
  cordova-android:
    name: Cordova Android Workflow by hci
    environment:
      node: latest
      # java: latest
      # android: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          npm ci
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 11.0.20-amzn
          sdk install gradle 7.1.1

      - name: Add Android Platform
        script: |
          cordova platform add android
      - name: Build APK
        script: |
          keytool -genkeypair -v -keystore wolf.keystore -storepass @loopback211 -keyalg RSA -keysize 2048 -validity 10000 -alias lgarin211 -storetype PKCS12 -dname "CN=agus, OU=tinus, O=tobing, L=id, ST=id, C=id"
          cordova run android --release -- --keystore=./wolf.keystore --storePassword=@loopback211 --alias=lgarin211 --password=@loopback211
      #   cordova build android
      # - name: Sign APK
      #   script: |
      #     jarsigner \
      #       -sigalg SHA1withRSA \
      #       -digestalg SHA1 \
      #       -keystore $CM_KEYSTORE_PATH \
      #       -storepass $CM_KEYSTORE_PASSWORD \
      #       -keypass $CM_KEY_PASSWORD \
      #       platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
      #       $CM_KEY_ALIAS
      #     $ANDROID_HOME/build-tools/30.0.3/zipalign \
      #       -v 4 \
      #       platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
      #       app-release.apk
      - name: Upload APK
        script: |
          echo "Deploying app to Codemagic..."
          curl -v -X POST \
            -F "file=/Users/builder/clone/platforms/android/app/build/outputs/apk/debug/app-debug.apk" \
            -H "x-auth-token: $CM_API_TOKEN" \
            -H "content-type: multipart/form-data" \
            https://api.codemagic.io/artifacts/upload
    artifacts:
      - /Users/builder/clone/platforms/android/app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - lagustinus211@gmail.com
